[package]
name = "rust-daemon"
version = "1.0.2"
edition = "2021"

[dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "c4efffcf6733b761eae9a2bb69306b34e37a005f", default-features = false, features = [
    "tcp", "noise", "yamux", "tokio", "macros",
    "request-response", "json", "kad", "identify", "autonat", "quic",
    "relay", "dcutr",
] }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.11"
prost = "0.12"
futures = "0.3"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
base64 = "0.22"
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }

[build-dependencies]
tonic-build = "0.11"
