CREATE TABLE IF NOT EXISTS affiliate_partners (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(255) NULL,
  code VARCHAR(40) NOT NULL,
  status ENUM('active','paused','blocked') NOT NULL DEFAULT 'active',
  commission_percent DECIMAL(5,2) NOT NULL DEFAULT 10.00,
  commission_months INT UNSIGNED NOT NULL DEFAULT 12,
  client_cap_eur DECIMAL(12,2) NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_affiliate_code (code),
  KEY idx_affiliate_user (user_id),
  KEY idx_affiliate_status (status),
  CONSTRAINT fk_affiliate_partner_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_attributions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  partner_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  referral_code VARCHAR(40) NOT NULL,
  source VARCHAR(80) NULL,
  first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  attributed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  status ENUM('active','expired','void','fraud_review') NOT NULL DEFAULT 'active',
  ip_hash CHAR(64) NULL,
  user_agent_hash CHAR(64) NULL,
  metadata_json LONGTEXT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_affiliate_attribution_user (user_id),
  KEY idx_affiliate_attr_partner (partner_id, attributed_at),
  KEY idx_affiliate_attr_status (status, expires_at),
  CONSTRAINT fk_affiliate_attr_partner FOREIGN KEY (partner_id) REFERENCES affiliate_partners(id) ON DELETE CASCADE,
  CONSTRAINT fk_affiliate_attr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_commission_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  partner_id BIGINT UNSIGNED NOT NULL,
  attribution_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  source_type VARCHAR(80) NOT NULL,
  source_id VARCHAR(120) NOT NULL,
  customer_amount_eur DECIMAL(12,6) NOT NULL DEFAULT 0,
  commission_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  commission_eur DECIMAL(12,6) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'EUR',
  status ENUM('pending','approved','paid','void','fraud_review') NOT NULL DEFAULT 'pending',
  metadata_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP NULL,
  paid_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_affiliate_commission_source (source_type, source_id, partner_id),
  KEY idx_affiliate_commission_partner (partner_id, created_at),
  KEY idx_affiliate_commission_status (status, created_at),
  CONSTRAINT fk_affiliate_commission_partner FOREIGN KEY (partner_id) REFERENCES affiliate_partners(id) ON DELETE CASCADE,
  CONSTRAINT fk_affiliate_commission_attr FOREIGN KEY (attribution_id) REFERENCES affiliate_attributions(id) ON DELETE CASCADE,
  CONSTRAINT fk_affiliate_commission_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
