CREATE TABLE IF NOT EXISTS enterprise_customer_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  quote_id BIGINT UNSIGNED NULL,
  company VARCHAR(160) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(160) NOT NULL,
  offer VARCHAR(40) NOT NULL,
  model_choice VARCHAR(140) NULL,
  sla_tier VARCHAR(40) NOT NULL DEFAULT 'standard',
  privacy_level VARCHAR(40) NOT NULL DEFAULT 'standard',
  dataset_gb DECIMAL(12,2) NOT NULL DEFAULT 0,
  fine_tuning TINYINT(1) NOT NULL DEFAULT 0,
  dedicated_workers INT UNSIGNED NOT NULL DEFAULT 0,
  monthly_estimate_eur DECIMAL(12,2) NOT NULL DEFAULT 0,
  setup_estimate_eur DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'scoping',
  project_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_enterprise_projects_status (status, updated_at),
  KEY idx_enterprise_projects_quote (quote_id),
  CONSTRAINT fk_enterprise_project_quote FOREIGN KEY (quote_id) REFERENCES enterprise_quote_requests(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
