# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vryx_pb2 as vryx__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vryx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Inférence locale (VPS ou worker via gRPC).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/vryx.InferenceService/Process',
                request_serializer=vryx__pb2.TensorData.SerializeToString,
                response_deserializer=vryx__pb2.ProcessedTensorData.FromString,
                _registered_method=True)
        self.ProcessStream = channel.unary_stream(
                '/vryx.InferenceService/ProcessStream',
                request_serializer=vryx__pb2.TensorData.SerializeToString,
                response_deserializer=vryx__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.ReportCapabilities = channel.unary_unary(
                '/vryx.InferenceService/ReportCapabilities',
                request_serializer=vryx__pb2.WorkerCapabilities.SerializeToString,
                response_deserializer=vryx__pb2.CapabilitiesAck.FromString,
                _registered_method=True)
        self.PingShardRuntime = channel.unary_unary(
                '/vryx.InferenceService/PingShardRuntime',
                request_serializer=vryx__pb2.ShardInit.SerializeToString,
                response_deserializer=vryx__pb2.ProcessedTensorData.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Inférence locale (VPS ou worker via gRPC).
    """

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCapabilities(self, request, context):
        """Capacités déclarées par le worker (RAM, device) pour le scheduler tensor-parallèle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingShardRuntime(self, request, context):
        """Vérification / warmup du runtime shard éphémère (sans persistance disque).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=vryx__pb2.TensorData.FromString,
                    response_serializer=vryx__pb2.ProcessedTensorData.SerializeToString,
            ),
            'ProcessStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessStream,
                    request_deserializer=vryx__pb2.TensorData.FromString,
                    response_serializer=vryx__pb2.StreamChunk.SerializeToString,
            ),
            'ReportCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCapabilities,
                    request_deserializer=vryx__pb2.WorkerCapabilities.FromString,
                    response_serializer=vryx__pb2.CapabilitiesAck.SerializeToString,
            ),
            'PingShardRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.PingShardRuntime,
                    request_deserializer=vryx__pb2.ShardInit.FromString,
                    response_serializer=vryx__pb2.ProcessedTensorData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vryx.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vryx.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Inférence locale (VPS ou worker via gRPC).
    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vryx.InferenceService/Process',
            vryx__pb2.TensorData.SerializeToString,
            vryx__pb2.ProcessedTensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vryx.InferenceService/ProcessStream',
            vryx__pb2.TensorData.SerializeToString,
            vryx__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vryx.InferenceService/ReportCapabilities',
            vryx__pb2.WorkerCapabilities.SerializeToString,
            vryx__pb2.CapabilitiesAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingShardRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vryx.InferenceService/PingShardRuntime',
            vryx__pb2.ShardInit.SerializeToString,
            vryx__pb2.ProcessedTensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
